### ISSUE TITLE
flask_msearch.whoosh_backend not found.

### ISSUE THREAD

**Issue by pleycpl** [honmaple/flask-msearch#10]
```python
 Original exception:
web | 
web | ImportError: module 'flask_msearch' has no attribute 'whoosh_backend'
web | 
web | During handling of the above exception, another exception occurred:
web | 
web | Traceback (most recent call last):
web |   File "web/run.py", line 16, in <module>
web |     search.init_app(app)
web |   File "/usr/local/lib/python3.6/site-packages/flask_msearch/__init__.py", line 37, in init_app
web |     "flask_msearch.whoosh_backend.WhooshSearch")
web |   File "/usr/local/lib/python3.6/site-packages/werkzeug/utils.py", line 443, in import_string
web |     sys.exc_info()[2])
web |   File "/usr/local/lib/python3.6/site-packages/werkzeug/_compat.py", line 137, in reraise
web |     raise value.with_traceback(tb)
web |   File "/usr/local/lib/python3.6/site-packages/werkzeug/utils.py", line 431, in import_string
web |     module = import_string(module_name)
web |   File "/usr/local/lib/python3.6/site-packages/werkzeug/utils.py", line 443, in import_string
web |     sys.exc_info()[2])
web |   File "/usr/local/lib/python3.6/site-packages/werkzeug/_compat.py", line 137, in reraise
web |     raise value.with_traceback(tb)
web |   File "/usr/local/lib/python3.6/site-packages/werkzeug/utils.py", line 436, in import_string
web |     raise ImportError(e)
web | werkzeug.utils.ImportStringError: import_string() failed for 'flask_msearch.whoosh_backend.WhooshSearch'. Possible reasons are:
web | 
web | - missing __init__.py in a package;
web | - package or module path not included in sys.path;
web | - duplicated package or module name taking precedence in sys.path;
web | - missing module, class, function or variable;
web | 
web | Debugged import:
web | 
web | - 'flask_msearch' found in '/usr/local/lib/python3.6/site-packages/flask_msearch/__init__.py'.
web | - 'flask_msearch.whoosh_backend' not found.
```

After i installed woosh package with manuel way, i runned again. Then,

```python
Traceback (most recent call last):
web |   File "web/run.py", line 16, in <module>
web |     search.init_app(app)
web |   File "/usr/local/lib/python3.6/site-packages/flask_msearch/__init__.py", line 43, in init_app
web |     self._backend = backend(app, self.db, self.analyzer)
web |   File "/usr/local/lib/python3.6/site-packages/flask_msearch/backends.py", line 45, in __init__
web |     self.init_app(app)
web |   File "/usr/local/lib/python3.6/site-packages/flask_msearch/whoosh_backend.py", line 159, in init_app
web |     models_committed.connect(self._index_signal)
web |   File "/usr/local/lib/python3.6/site-packages/flask/signals.py", line 33, in _fail
web |     raise RuntimeError('signalling support is unavailable '
web | RuntimeError: signalling support is unavailable because the blinker library is not installed.
```

After i installed blinker package with manuel way,  it worked. Everything is fine.

I think we must add woosh and blinker package in [requires](https://github.com/honmaple/flask-msearch/blob/master/setup.py#L29)

**Comment by honmaple** [comment]
flask-msearch's default backend is `whoosh`, but the backend is not unique, it can be `whoosh`, `simple` or `elasticsearch`,it will require different dependencies when using different backends.

Beause I use `import_string` to import different backends, the error is not obvious, I  will add this to README. Thanks for your report.
