### ISSUE TITLE
TypeError when deleting records in database

### ISSUE THREAD

**Issue by babunoel** [honmaple/flask-msearch#13]
When I delete a record in my database, I get this error when I have flask-msearch configured:
`TypeError: delete_by_term() got an unexpected keyword argument 'termtext'`. I think this has something to do with the whoosh backend. Here is the entire error log:
```
Traceback (most recent call last):
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\babunoel\my-app\app\routes.py", line 139, in delete_accomplishments
    search.delete_index()
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_msearch\backends.py", line 141, in delete_index
    return self.create_index(model, delete=True, yield_per=yield_per)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_msearch\backends.py", line 108, in create_index
    return self.create_all_index(update, delete)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_msearch\backends.py", line 121, in create_all_index
    ix = self.create_index(m, update, delete, yield_per)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_msearch\backends.py", line 112, in create_index
    self.create_one_index(instance, update, delete, False)
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_msearch\backends.py", line 91, in create_one_index
    ix.delete(fieldname='id', termtext=str(instance.id))
  File "C:\Users\babunoel\my-app\venv\lib\site-packages\flask_msearch\whoosh_backend.py", line 138, in delete
    return self._writer.delete_by_term(**kwargs)
TypeError: delete_by_term() got an unexpected keyword argument 'termtext'
```

**Comment by honmaple** [comment]
Thank you for your report, the problem is fixed, please use `pip install flask-msearch --upgrade` to upgrade package.

**Comment by babunoel** [comment]
Thanks so much @honmaple
