### ISSUE TITLE
This session is in 'committed' state; no further SQL can be emitted within this transaction

### ISSUE THREAD

**Issue by inamilu** [honmaple/flask-msearch#24]
I'm trying to write an import script that adds some data into the database and indexes them with flask-msearch, but I'm getting an error when importing the data.

The simplified code is as follows:
```
app = Flask(__name__)

# SQLAlchemy configurations
app.config['SQLALCHEMY_DATABASE_URI'] = <my-db-uri>
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
# Msearch configurations
app.config['MSEARCH_INDEX_NAME'] = 'msearch'
app.config['MSEARCH_BACKEND'] = 'whoosh'
app.config['MSEARCH_PRIMARY_KEY'] = 'id'
app.config['MSEARCH_ENABLE'] = True

db = flask_sqlalchemy.SQLAlchemy(app)
search = Search(app, db=db)

class MyClass(db.Model):
    __tablename__ = 'my_table'
    __searchable__ = ['first_param']

    id = db.Column(db.Integer, primary_key=True)
    first_param = db.Column(db.Unicode)
    second_param = db.Column(db.Unicode)
    third_param = db.Column(db.Unicode)

def load_data(filepath, session):
    try:
        # Read some file
        with open(filepath, 'r', encoding=encoding) as file:
            datareader = csv.reader(file)
            
            for row in datareader:
                session.add(MyClass(<add params from row>))

            session.commit()

            return True
    except Exception as e:
        return False

if __name__ == '__main__':
    db.create_all()
    session = db.session
    data_loaded = load_data(filepath = <my-file-path>, session = session)
```

The following error is thrown:
```
This session is in 'committed' state; no further SQL can be emitted within this transaction.
Traceback (most recent call last):
  File "data_importer_w_msearch.py", line 171, in load_data
    session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 468, in commit
    self.session.dispatch.after_commit(self.session)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 219, in after_commit
    models_committed.send(session.app, changes=list(d.values()))
  File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.7/site-packages/flask_msearch/backends.py", line 165, in _index_signal
    self.create_one_index(instance)
  File "/usr/local/lib/python3.7/site-packages/flask_msearch/whoosh_backend.py", line 190, in create_one_index
    attrs[field] = str(getattr(instance, field))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 579, in get
    value = state._load_expired(state, passive)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 592, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 698, in load_scalar_attributes
    only_load_props=attribute_names)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
    return q.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
    **kw
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 998, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 258, in _assert_active
    "This session is in 'committed' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.
```

Now, when I remove the` __searchable__` from `MyClass`, it works fine and the data is imported. So it probably is related to `flask-msearch` somehow.

**Comment by honmaple** [comment]
It's really strange, I tested it work well.
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_msearch import Search

app = Flask(__name__)

# SQLAlchemy configurations
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
# Msearch configurations
app.config['MSEARCH_INDEX_NAME'] = "msearch"
app.config['MSEARCH_BACKEND'] = 'whoosh'
app.config['MSEARCH_PRIMARY_KEY'] = 'id'
app.config['MSEARCH_ENABLE'] = True

db = SQLAlchemy(app)
search = Search(app, db=db)


class MyClass(db.Model):
    __tablename__ = 'my_table'
    __searchable__ = ['first_param']

    id = db.Column(db.Integer, primary_key=True)
    first_param = db.Column(db.Unicode)
    second_param = db.Column(db.Unicode)
    third_param = db.Column(db.Unicode)


def load_data(session):
    try:
        for i in range(40):
            user = MyClass(
                first_param="first user{0} name".format(i),
                second_param="second user{0} name".format(i),
                third_param="third user{0} name".format(i))
            session.add(user)
            if i == 20:
                raise ValueError("aaa")
        session.commit()
        return True
    except Exception as e:
        return False


if __name__ == '__main__':
    db.create_all()
    session = db.session
    data_loaded = load_data(session=session)
```

**Comment by lepri** [comment]
Hi @honmaple!

I got the same error and I'm using before_models_committed signal instead of models_committed and everything is working well.

The error occurs when we get a related field from model.

**Comment by ragunyrasta** [comment]
Yes. But when you use before_models_committed instead of models_committed in flask_sqlalchemy/track_modifications.py at the point where the exception is raised, the bug goes away but, the index doesn't auto-update on data change.
