### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by SLey3** [honmaple/flask-msearch#54]
When I init the module with the `Search()` class, I get the following error below:

```
Traceback (most recent call last):
  File "c:\Users\ghub4\Projects_Website\ProjectsWebsite\__init__.py", line 14, in <module>
    from ProjectsWebsite.admin import admin
  File ".\ProjectsWebsite\__init__.py", line 14, in <module>
    from ProjectsWebsite.admin import admin
  File ".\ProjectsWebsite\admin.py", line 8, in <module>
    from ProjectsWebsite.database.models import User, Article, user_datastore
  File ".\ProjectsWebsite\database\models\__init__.py", line 5, in <module>
    from ProjectsWebsite.database.models._models import *
  File ".\ProjectsWebsite\database\models\_models.py", line 143, in <module>
    search.create_index(Article)
  File "C:\Users\ghub4\Projects_Website\ProjectEnv\lib\site-packages\flask_msearch\__init__.py", line 46, in __getattr__
    return getattr(self._backend, name)
  File "C:\Users\ghub4\Projects_Website\ProjectEnv\lib\site-packages\flask_msearch\__init__.py", line 46, in __getattr__
    return getattr(self._backend, name)
  File "C:\Users\ghub4\Projects_Website\ProjectEnv\lib\site-packages\flask_msearch\__init__.py", line 46, in __getattr__
    return getattr(self._backend, name)
  [Previous line repeated 964 more times]
RecursionError: maximum recursion depth exceeded
```
It seems the `__getattr__` somehow exceeded the Recursion limit.
Below is my config if it is something in my config that is causing this to happen
```python
app.config["MSEARCH_INDEX_NAME"] = mkdtemp()
app.config["MSEARCH_PRIMARY_KEY"] = 'id'
app.config["MSEARCH_BACKEND"] = 'whoosh'
app.config["MSEARCH_LOGGER"] = logging.DEBUG
```

**Comment by SLey3** [comment]
I forgot to mention that the Recursion error originates in the `__getattr__` function in the `Search` class.

**Comment by honmaple** [comment]
You should init app by `Search(app)` or `search.init_app(app)` before using `Post.query.msearch`

**Comment by SLey3** [comment]
I done that which still get's the error

**Comment by SLey3** [comment]
> You should init app by `Search(app)` or `search.init_app(app)` before using `Post.query.msearch`

I've done the initialization part for this class which still gets the recursion error and I have not used `Post.query.msearch` yet.
