### ISSUE TITLE
importing issue from werkzeug.utils

### ISSUE THREAD

**Issue by BandarHL** [honmaple/flask-msearch#61]
Error log:
```
Traceback (most recent call last):
  File "/Users/bandaralruwaili/PycharmProjects/WaiterSA/run.py", line 3, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/Users/bandaralruwaili/PycharmProjects/WaiterSA/app/__init__.py", line 51, in create_app
    search.init_app(app)
  File "/Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/flask_msearch/__init__.py", line 33, in init_app
    backend = import_string(
              ^^^^^^^^^^^^^^
  File "/Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/werkzeug/utils.py", line 611, in import_string
    raise ImportStringError(import_name, e).with_traceback(
  File "/Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/werkzeug/utils.py", line 603, in import_string
    module = __import__(module_name, globals(), locals(), [obj_name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/flask_msearch/simple_backend.py", line 15, in <module>
    from .backends import BaseBackend
  File "/Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/flask_msearch/backends.py", line 15, in <module>
    from flask.helpers import locked_cached_property
werkzeug.utils.ImportStringError: import_string() failed for 'flask_msearch.simple_backend.SimpleSearch'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'flask_msearch' found in '/Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/flask_msearch/__init__.py'.
- 'flask_msearch.simple_backend' not found.

Original exception:

ImportError: cannot import name 'locked_cached_property' from 'flask.helpers' (/Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/flask/helpers.py)

```

**Comment by ragunyrasta** [comment]
Try changing line 16 in the file  /Users/bandaralruwaili/PycharmProjects/WaiterSA/.venv/lib/python3.11/site-packages/flask_msearch/backends.py  from:

from flask_sqlalchemy import models_committed  
to 
from flask_sqlalchemy.track_modifications import models_committed

and see if it works. Looks like flask-sqlalchemy changed the default location of models_commited leading to this issue

**Comment by BandarHL** [comment]
i fixed this issue by not using the import_string:
```python
        if msearch_backend == 'simple':
            from flask_msearch.simple_backend import SimpleSearch
            backend = SimpleSearch
        elif msearch_backend == 'whoosh':
            from flask_msearch.whoosh_backend import WhooshSearch
            backend = WhooshSearch
        elif msearch_backend == 'elasticsearch':
            from flask_msearch.elasticsearch_backend import ElasticSearch
            backend = ElasticSearch
        else:
            raise ValueError(f'Backend {msearch_backend} does not exist.')
 ```
 But there is another problem that cannot import ```locked_cached_property``` because flask changes it from ```flask.helpers```

**Comment by BandarHL** [comment]
Flask deprecate the ```locked_cached_property``` 
https://github.com/pallets/flask/blob/c2f65dd1cfff0672b902fd5b30815f0b4137214c/CHANGES.rst#L83

**Comment by BandarHL** [comment]
@honmaple  The summary here to fix issues with new versions of Flask is:
- Use regular import statements instead of ```import_string```.
- Use ```cached_property``` from werkzeug.utils instead of ```locked_cached_property``` because is deprecated.
